import mysql.connector

connection = mysql.connector.connect(host='localhost',
                                     port='3306',
                                     user='root',
                                     password='TstwTdtct42',
                                     database='ETC_CARS'
                                     )

cursor = connection.cursor()

cursor.execute("SELECT * FROM `all_cars`;")

records = cursor.fetchall()
for r in records:
    print(r)

cursor.execute("\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-1Q29FZ', 9763);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-6V8JZ4', 5375);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-8TYWHQ', 4028);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-57A032', 5953);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-6VKBHV', 6813);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-30HAJF', 1159);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-7R6442', 1052);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-0KD3JQ', 6754);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-8I7UAT', 1032);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-416NVM', 4764);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-0GWNF2', 6788);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-2YCBGF', 1598);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4FUGL4', 7678);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-6L2S5N', 445);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-7IGI7H', 7371);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-5WQRNN', 8873);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-1ULSC8', 9505);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-7M05RI', 8476);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-4I4N5V', 1337);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-0H94WV', 4070);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-9NZB44', 7744);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-82LZ4L', 8428);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-0FYPEC', 3824);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-4TTY5M', 29);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-4TJ4E8', 2186);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-30V2G3', 5946);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-6HQ3C2', 2320);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-5U7756', 4485);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-9H14H3', 5082);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-8PVRL3', 9263);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-0AHSJY', 5462);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-1TXVSQ', 1346);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-7CZL56', 8167);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-6U3P42', 9354);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-8590V3', 3955);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-92Y05V', 8672);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-33SAGT', 5099);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-1RSRG0', 4455);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-81XHUZ', 9645);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-1MSQSW', 2178);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-6KJ00Z', 8804);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-4AQPYK', 7319);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-882GUW', 4690);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-9472D1', 5979);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-0TB0Q1', 521);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-9Q1DQW', 53);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-91VNAA', 1250);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-3130ZI', 279);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-61P247', 8877);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-09XIAS', 9383);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-70HAIA', 7913);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-6X85E8', 5576);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-49N867', 3420);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3M569V', 5480);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-0XJM06', 4963);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-3GBG5I', 579);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-3G408F', 3098);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-39G0RC', 8399);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-6SN3B1', 671);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-53MYW7', 5675);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-3CQ21X', 2646);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-5ZE9DR', 6979);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2VYL63', 3958);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-6SCZYG', 8854);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1Q8AFA', 7554);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-3N56QH', 7853);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-6HJ7E9', 2347);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-4SFKS5', 6365);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-9E7V1G', 8453);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5C1022', 7876);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-3D03Y8', 3924);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-2CX9HG', 3611);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-35ZC4J', 6018);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-4S2SP3', 1847);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-6WI5MV', 5243);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-03BEHC', 4191);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3D9MCI', 4515);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-72TG6N', 318);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-2R6DH2', 8576);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-684JQR', 6212);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-0YSDM2', 5383);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-34UDGD', 7861);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-0VQYC4', 7692);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-8FQZ77', 3369);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-206NTK', 1109);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-2NBE1L', 3188);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-8EIZMG', 4285);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-0GZG1S', 9283);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-5SPQC4', 7157);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-62WBSL', 8884);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-83JZT8', 8975);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-7KUT2L', 5605);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-76JB74', 4566);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-3TCLPC', 9939);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-3Q1GPM', 2000);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-5D04FT', 4223);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-7NMQEL', 1223);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-7W2LI9', 569);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-9ZW3MD', 7594);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-7TMIVL', 2899);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-46YISP', 8850);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-5EVFIV', 4386);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-42WFXL', 6413);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-75T70U', 8985);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-52F29D', 490);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-6FIT5M', 4359);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-480UCZ', 9716);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-0CFCDE', 8686);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-82QR1C', 926);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-9HLXY5', 4545);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-86FYHQ', 3527);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-26BW6Z', 1684);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1MUZKI', 4920);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-5NUR2Q', 3572);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-38TK53', 3167);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-28K6F6', 2124);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-6YLFZY', 3925);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-5ZWZ8U', 8242);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5S18YR', 3866);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-8T4N7L', 9401);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-5F0Z32', 7927);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-5Y2KNU', 2249);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-46ZS4Q', 8175);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-5ANCEN', 158);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-0NH8AV', 2138);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-65ZA8E', 3889);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-4F446F', 4665);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-9JS9I0', 1194);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-8B8IVW', 8883);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-2RHRM3', 2216);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-7C1DF2', 30);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-63TTWN', 1256);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-1JZE07', 5336);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-92MJSN', 3272);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-3J3ZN6', 5795);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-4Z2HYI', 2395);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-6P2N71', 2124);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-773JI7', 8806);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-03C6ZN', 136);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-6EGLNC', 9029);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-87SETL', 7984);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-4BNRG8', 6203);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-1L26VF', 8831);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3HX4DJ', 4308);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-0JSY3C', 319);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-41PZRM', 216);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-1UUYUM', 2603);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-1KX8XF', 1629);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-712M8E', 6760);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-5CQ219', 5614);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-59BF20', 3565);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-6V9B8T', 159);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-4FPDWQ', 7127);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-5XW1FT', 6705);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4V6550', 6930);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-3VVTN0', 9159);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2J9MLZ', 361);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-3NA1G8', 8483);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-49XF83', 5346);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-4W25X4', 3054);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-6QKETK', 6495);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-05PNVI', 2036);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-1GULSC', 3342);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-65V4V9', 6395);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-58IJ3G', 8935);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-7GCTAN', 8767);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-97EVL6', 4555);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-0ILNYF', 2818);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-3F800C', 2984);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-07S748', 6859);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5B3KC4', 9486);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-2VGFCD', 6739);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-4EISRS', 447);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-53T0YL', 7461);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-4TUX0S', 1377);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-01IRSX', 1751);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-2W9YAI', 8611);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-0IZFK9', 2497);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4MT94S', 9807);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-0ISXJ5', 3359);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2966A2', 7334);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-8YLV9Q', 9062);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-27CXQR', 2356);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-6E48JW', 8934);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-4MWUHK', 5219);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-91SMIH', 7970);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-5V4LNG', 6918);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-67VENS', 1424);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-2VP9YK', 3224);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-2FW0DT', 359);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-0L654Q', 6348);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-47G1DH', 1782);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-3CU7LB', 8450);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-2235GA', 3556);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-1XAI25', 5531);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-7XNX96', 4895);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-6A6LBF', 9741);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-64RTT5', 332);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-34ZE6A', 5435);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3PKUIK', 1891);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-2D7710', 7412);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2C6LWL', 2709);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-950QBK', 206);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-1RHQC5', 2238);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-5RPR5I', 5543);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-1DHPRH', 393);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-4X878W', 4610);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-43E9UX', 4537);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-8BHMLV', 160);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-4JHVFE', 5086);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-10EMTZ', 5070);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-4INJ7L', 71);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-7L5QXY', 4344);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-9IVJKL', 6818);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-27G6FA', 3215);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-8FASXW', 5888);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-2II6BA', 7462);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-61CVCX', 7909);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4KI2E0', 4627);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-6WSQTP', 6863);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-51JWG8', 1660);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-7NWB8F', 1606);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-33ZEPT', 2200);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-95E5QQ', 9022);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-1V1QXK', 2166);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-5S1LSI', 4616);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-0VEIFR', 121);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-8PVLDQ', 1379);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-6GNPB3', 4124);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-5FB0P6', 5049);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-3CZ7KW', 3193);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-7LPJLX', 8045);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-1XMDGX', 5853);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-6HT7FX', 3290);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-7KC1HE', 4455);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-2CNN62', 8903);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-137G1E', 7512);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-30CXTE', 4040);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-8Z439X', 5072);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3FWQB0', 6219);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-9YVAG4', 4926);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-4ZZ54D', 4115);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-1H5CRI', 8136);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-232JNA', 7895);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0G025Y', 9262);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-8ANKGB', 1545);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-7FW953', 8025);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-3SPSCM', 7418);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-233IFM', 666);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-2LZ3XZ', 338);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5141IS', 70);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-3KZYER', 1707);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-4M853G', 1826);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-92THRB', 5798);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-4P77YW', 2164);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-28UMY5', 7014);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-0K9WH4', 5792);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-8YJ566', 5220);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-5ETHD9', 5456);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-0E1QSD', 8807);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-939B65', 50);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5CGFSF', 8253);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-2SMAPN', 8090);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-4PJB1J', 4402);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-0ZZSSW', 9866);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-4SLVE8', 291);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-7DVG4I', 1826);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-1211TE', 9501);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1ANJWN', 5076);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-6JVJ6Y', 2214);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3SC41E', 9543);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-56HB6F', 5046);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-58E2A4', 272);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-9I2IF0', 7607);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3NG8FY', 5372);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-55MD80', 1836);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-6BIZWG', 4776);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-91XL17', 2216);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-6VN3BY', 8253);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-9TV3P9', 3763);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-9K2I31', 2813);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-7W5N7J', 552);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4MLF9M', 2023);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-7H8EV6', 6718);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-1QRPSH', 8141);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-5TX98J', 8080);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-8J16MN', 5600);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-72MLTP', 142);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-45NPDG', 7356);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-3EJ2AQ', 2380);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-62Z5WS', 8500);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-19I7A4', 3542);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-6BLQY2', 3564);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-84QMNT', 5929);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-6AAI62', 302);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-5WK684', 4054);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-3IBNG4', 2746);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-4AIL6M', 474);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-8ZY8SZ', 444);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-9C93S1', 3418);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-936KPW', 9130);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-1ZUXF4', 3618);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-7LWWHD', 4126);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-6QTFBX', 7507);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-3KYJ7G', 8658);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-3SY883', 4186);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0BHPWB', 3784);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-71FXE3', 6888);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-73X5VY', 1364);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-72JNB7', 5302);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4KP17N', 3189);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-1Y27NC', 4850);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-09FMI8', 9942);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-0WZWN4', 6715);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-8J9SQ1', 4369);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-2L6FL7', 6528);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-6IBGRN', 9687);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-723YEE', 6951);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-30DDMZ', 4394);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-0IZC8K', 2078);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-48H64P', 6593);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-59NPE4', 9955);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-6YIFM6', 8718);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0B7XT5', 6737);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-7IB8NN', 269);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-8T4SNM', 6599);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-5Z0VKC', 7086);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-1VF0A2', 9950);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-2PTTZH', 3198);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-6ND6SJ', 3813);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4Q9RZ8', 7392);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-77VK23', 5854);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-3CND40', 3583);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-8T7P18', 8052);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-1F0M9W', 9105);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-8ZE42L', 1059);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-7J1PTQ', 1049);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-8F4CHE', 9977);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1PY0WX', 7574);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-27L2SS', 1943);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-8B5BSZ', 8483);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-3P822V', 9798);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-98S0S5', 3106);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-2KEC3I', 6992);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-1DSWUN', 7409);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-5BXH50', 9599);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-8LICFU', 7864);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5RJLV6', 1149);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-8XUPGK', 5948);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-6LL44Y', 3866);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-9CWBBL', 6278);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-8H4N2F', 6634);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5JW48Z', 8343);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-7NES2K', 6181);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-02HTGQ', 4746);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-2AJWBU', 7677);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-6MJIGC', 6489);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-95Y9BW', 6587);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-6I4QFX', 7386);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-8FP9X7', 9356);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-3LJG29', 6418);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-7X21V1', 3628);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-58ECJL', 5512);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-5RARH1', 5395);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-8LNY3J', 9969);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-3SUE4W', 8724);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-06ACK3', 49);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-3HL1RZ', 5574);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-5V5H0L', 9929);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-4C9X83', 8694);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1A3EYF', 4137);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-2AAUSL', 9052);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-34LG39', 5314);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-0Z1AP2', 8129);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3N4RFG', 6021);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-1C2912', 1800);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3KSRTW', 1787);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-0VGQ2X', 1338);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-6TQYM4', 48);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-1057UB', 5974);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-57195L', 5774);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-6BUK6M', 5098);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-44R7GC', 5416);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1IFBAM', 6803);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-881PZ6', 8614);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-2TZ407', 2350);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-2JEDA3', 5731);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-88YXDC', 2680);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-1P43MX', 8001);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-6N2PEE', 5637);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-1L7WXH', 2655);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-8DW8S9', 1760);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-36TN2P', 8170);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2JEIMY', 6295);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-3EAIAA', 6788);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-4U1PW9', 2755);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-9LZX79', 8544);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-8LY13C', 7903);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-3ZBA0C', 8047);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-45IQ2K', 9873);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-11AKYY', 2008);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-4L1CVF', 8632);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-69UCGI', 4492);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-41LZEM', 6809);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-5TVBBW', 1196);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-9MAZRI', 2329);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-4RCKGH', 9025);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-44E325', 1557);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2X5VP0', 5938);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-1W9Z7L', 4022);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-98GXQG', 63);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-169TXE', 5566);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-45RIQ5', 3226);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-20814D', 5757);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-9ZXM33', 6346);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5RYTGQ', 5297);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-7SA8EA', 2952);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-2N4XU5', 9614);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-9B7PVD', 3525);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-4NTDF8', 7911);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5204CL', 9974);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-38L948', 5985);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-404FFR', 3968);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-1M5GX5', 9364);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-7C7KUT', 2829);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-0B1KGI', 5374);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-9XH15C', 1925);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-6KIIUB', 3963);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2AHW8W', 5170);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-7WH9RN', 2100);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-6XZX1L', 6216);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0FWB0V', 3490);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-1HEV4S', 6401);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-50ALP1', 1701);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-7LUV6M', 2299);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-7VGENK', 4625);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-5FMMQR', 8547);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4JZL50', 8487);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0ZA83S', 5234);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-5U3K3R', 738);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-4363NG', 420);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-1YV5U0', 524);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-4YB5TT', 6674);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-9MARSI', 782);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-88VCMC', 3046);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-3LHG1U', 525);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-407DUH', 1331);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-77PACG', 404);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-04SSM2', 9513);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-91H1M6', 9801);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-94JNAD', 2869);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1E9BJZ', 6080);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-96ZZTR', 9534);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-1YRI9A', 6686);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-5WE0LE', 1683);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0RVB35', 888);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-58QXAM', 387);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-5NGSTG', 125);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-6BD2K0', 5071);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-9ITTHG', 7043);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-913BVG', 1923);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-2XTUI7', 2818);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-57SHW2', 3851);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2KCKUH', 8855);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-4HJHLN', 783);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-2779L4', 6602);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-6W194A', 9350);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-6YKEHA', 2433);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-05DRC6', 7560);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-892SUZ', 3270);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-7DS1ZA', 9011);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-7UFT9H', 1307);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-0LLECN', 8205);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-6ZGWHR', 3965);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-4VDE9I', 5567);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-12R2ML', 3722);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-079BD8', 1450);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-7I8YMJ', 7059);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-04NXLV', 2497);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1CHDWT', 1800);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-77T53R', 9035);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-4WJ8NI', 2413);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5243SJ', 2707);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-7ABHLR', 2146);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-9NEQPJ', 4931);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1NG9Q5', 9638);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-7BDRHB', 5292);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-71N2TR', 1000);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-99B0G9', 5244);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5SJZL4', 8371);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-1KQGZ6', 2269);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-29V4TN', 971);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-49XX6Z', 9451);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-19J4RR', 325);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-4Y1US2', 3511);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-51AU2U', 3230);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-2WN0W0', 1502);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-68EBF2', 9137);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-47T5J5', 3752);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-90CHTS', 9107);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-09CJN5', 7388);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-93QTP4', 7537);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-2CEB9E', 9228);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-7RIRG6', 5241);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-21N6RQ', 2654);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-6LFELB', 2553);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-09I5DA', 8237);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-50LUCI', 1983);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-4BG1FE', 2453);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-57BRM1', 7922);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-5CU9N5', 4436);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-1EBBPW', 4228);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-1CJ9UJ', 4654);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-3L2ZSY', 7097);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-0ZH7ND', 7862);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-3M4RR3', 6322);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-41U1WG', 3728);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-7ZB9WK', 53);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-0P6KJP', 352);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-7UQKLK', 1309);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-6H1FKW', 4541);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-2WZV62', 5747);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-4UKKKZ', 1638);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-57IQBR', 453);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-9NK0CF', 204);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-162GR9', 8653);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-2XP66U', 268);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-4C43SR', 9141);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-2ETBTA', 6845);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-4S05JK', 3926);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-1IL2R2', 4785);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-7KXNG9', 4782);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4K0ILM', 3943);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-3KBD9K', 7503);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-1DV1QK', 7372);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-5ANAMN', 9350);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-0ZUUV3', 7294);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0T1Y9D', 6905);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4K7W93', 508);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-14QYCN', 1148);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-1QJFWJ', 45);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-2AAXHR', 11);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-9LD6AA', 1475);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-0BER3G', 634);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-0SNTBB', 1983);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-8R7GK0', 2713);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-7PD9FU', 6381);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-0M2YUX', 719);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-9RC6ZN', 6101);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-7H6LRT', 6285);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3ECSSH', 3338);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-147N5Q', 6635);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1599T9', 4652);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-20T0D4', 5550);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-05IBHM', 6127);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-9KFU3R', 1265);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-885NSD', 8698);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-87UC2I', 9564);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-31MFXZ', 16);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-95KH51', 389);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-75PSXF', 3470);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-9DHASX', 7828);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-6N67YV', 2748);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-7KXENE', 3358);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-40NCD5', 7088);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-738Y7M', 9850);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-6RXQWS', 2237);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3KIEWM', 2902);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-1LW8ZN', 6989);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-885HCC', 9645);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-6KW04K', 3579);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-83PIFI', 7195);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1Z94EH', 3871);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-930I7S', 9038);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-72G3CV', 3438);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-52P29C', 4694);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-3AITXZ', 7150);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-4Y21JH', 4186);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-45VTPZ', 1185);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-60CRQC', 6411);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1UJX3Z', 1289);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-88IZD6', 7201);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-9309IL', 7534);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-72325E', 781);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-6J093U', 5366);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3KK7JE', 5442);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-7NLHKW', 5607);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-01IRTC', 3993);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2RIE03', 2268);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-5Y4SWN', 2467);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-9I47BB', 6997);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-5HQFFV', 5599);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-8YG395', 3435);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-5U0WR9', 9872);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-95NNRR', 7779);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-98L2WM', 8395);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-06I16L', 5924);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-8MT3UH', 7429);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-0REWWH', 4350);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-54C3J7', 3237);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-2SUSKL', 5785);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-7JC10K', 3180);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-74EPN0', 8559);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-3Z30C8', 2193);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-15AUUJ', 8592);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-3V3GH0', 5947);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-9WWJMU', 9677);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-0HY0LZ', 1201);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-432GU3', 484);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-1CJ078', 539);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-7ZUQDA', 8210);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-9F88J2', 5127);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-8GIKUJ', 250);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-58Z335', 7798);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-7I447C', 4976);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-6BY97J', 4132);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-8ZTQGD', 3108);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-37NJSZ', 6580);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-75JZN1', 5091);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-5V5S5E', 8609);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-2MESX8', 1913);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3CITSB', 2743);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-70UAKC', 6582);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-75ALTP', 8894);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-566LM9', 677);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-3CLUMD', 486);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-25RRWV', 3703);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-5KKTDK', 3554);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-0R9DDF', 3565);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-130N69', 5262);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-183XKA', 2409);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0VC4BU', 3501);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-6H81QS', 2831);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-8L3G3X', 1264);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2SDARL', 4729);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0AS7ML', 7125);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-20Z31I', 2786);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-3DGAZE', 3417);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-7BBSS6', 5302);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-6Y73DW', 3558);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-71GS8E', 1311);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-0ZF85K', 922);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-1827P1', 6029);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-7347MZ', 6005);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-280NM8', 8202);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-6C3SWE', 2344);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-8H0QZ2', 4685);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-8PHWDI', 820);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-6KK54L', 2049);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-3ZB6V0', 8633);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-09PY9T', 8873);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-3RTWVE', 18);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-64VFI0', 87);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2QJZD7', 9041);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-6FVATA', 4301);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-9J4M3U', 8529);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5P0744', 7758);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-00Q2DM', 8153);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-37V6I3', 1724);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-14SG53', 4434);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-2KZNZA', 9540);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-2G4UB4', 933);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-7I0U8F', 819);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-5M37BU', 7921);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-8YD9YJ', 4411);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-6R20VK', 9353);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-8XA49V', 7241);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-1GNLIS', 9367);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-4SBQ9A', 7896);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-62TDXR', 2361);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-4QDJLP', 2522);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-8A4136', 2411);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-9BJXFD', 8548);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-9TAK9Z', 8407);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-5A31UP', 9627);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-8S7WW2', 6303);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-7HLE17', 9103);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-8D4CEX', 6491);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-7VPLA3', 735);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4GGMI0', 1569);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-5V7NN9', 9683);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-7HWSYR', 780);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3WNKKA', 8730);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-9ZJ3NP', 282);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-2948WL', 8122);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-9P7QLA', 3347);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-2EKKZI', 6990);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-7I2ZTY', 6707);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-30C5LG', 8430);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-3UGLFL', 4554);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-39TBSB', 9973);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-2696FL', 9955);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-08LJQG', 2776);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-311SA2', 4500);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-9N7FHZ', 5106);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-0RAXNW', 4573);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0AW61N', 8597);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-0DZWTR', 5379);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-40XQ1D', 4320);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-2Y9IUH', 6815);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-7Y17D0', 6935);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-264U4I', 3115);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-7W012I', 2818);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-8CN2JM', 6916);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-9KE9TY', 5010);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-0KJ9DA', 3741);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-6YRKRU', 7739);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-7Z8QBJ', 9234);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2B5KGJ', 5991);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-14GDWA', 2430);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-8QMGQY', 255);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-96GF0C', 5187);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-5R5N1P', 7177);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-4D1PP5', 2306);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-8YMG7L', 8591);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-8MS302', 1060);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-32WDDQ', 2681);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-6NWXFP', 9506);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-2AMSVC', 9424);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2HT0A3', 9556);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-4KLZI9', 1338);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-4DIXWN', 7205);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-93U0A9', 1642);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-4KU720', 3759);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-188VAX', 9497);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-8UP3K6', 3692);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-17N72J', 6555);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-4XYFE9', 4497);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-8Z2KUJ', 6876);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-46VUAF', 5910);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-52QT30', 5320);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-50ZGJ4', 2695);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-0R5TXU', 9732);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-2YVJTR', 3505);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-3CH0M8', 7476);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-1XBJQ2', 3153);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-0RUSVW', 7093);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-2X6MG1', 6928);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-4W3I9H', 7027);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-4RXBUB', 5545);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-9M0ZQ2', 3294);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-23D76G', 1967);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-2MLZW2', 1110);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-21BMG0', 9410);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-6JD3KC', 2686);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1RP7FM', 3390);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5GPWFT', 1671);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-10DAST', 3557);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-0G3QH1', 1208);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-76S1CM', 234);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3PTPNZ', 9556);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-80EXZA', 3607);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-3K93PC', 5189);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-7LAV28', 6412);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-3DJ3EE', 7503);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-77YQ2H', 3581);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-7ESYY8', 3570);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-7EMYA2', 7814);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-4P1DQL', 7445);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-6F4AYA', 3066);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-79VFTC', 245);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-9C5902', 4523);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-9IBXHN', 949);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-5D2E5W', 1020);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-1WTV7F', 5086);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-7JX9T1', 4258);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-9R3EUX', 7018);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-65GD23', 4313);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-5KV8NY', 9609);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-78AL4G', 9757);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-6JUMS8', 8696);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-7ZEP1T', 3166);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-6RHJMV', 6663);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-0HFHBD', 7874);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-3QA19Y', 1559);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-3Y7HGI', 6071);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-1UPA8W', 6812);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-00SWX6', 6912);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-00RP7E', 5872);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-9C8P71', 5057);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-06TE21', 5230);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-057VLI', 4437);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-6V8PFL', 9954);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-27KKF6', 2858);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-8NUPUF', 9418);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-5NCKRD', 6600);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-8XW5DC', 940);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-1J5B5P', 7242);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-3V1EJE', 8991);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-581V6S', 7752);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-0T42NH', 2004);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-9SRU1U', 266);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-1VREY3', 2574);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-1XIG8I', 1099);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-8HK9X4', 5519);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-3PBMBA', 9466);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-81WRPI', 7506);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-4I357T', 3375);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3WF672', 1657);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-9TQ1F1', 2448);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-6KXZ17', 9011);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-6I80L6', 6125);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4W8WDF', 7139);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2RISFJ', 1231);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-7ZKB0G', 7407);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-2GCRMM', 9019);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-4EHWV1', 1349);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-7L0T17', 336);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-4GQDCC', 5765);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-3DPCH4', 544);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-0YFUDP', 8677);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-9XTI69', 4258);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-7DCKJ5', 6046);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-3JHKVP', 1360);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-0ZBTPI', 6319);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-7UG6NV', 9736);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-5I3Y3F', 2454);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-3NLT3Y', 5368);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-0Q1IVP', 8301);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-0EP5L5', 3618);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-46KS0D', 54);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-5TK3LB', 1986);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-46I2SA', 7092);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-8BN5NZ', 2648);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-2S71W0', 9924);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-26MDBS', 9463);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-28P73W', 6129);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-7HJMZB', 6516);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-2I9K3J', 6352);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-2UJL53', 6630);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-08154G', 1511);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-1EQF8Y', 4508);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-6QRZ89', 6711);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-7KHDUT', 4483);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-09QVQC', 8224);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-71U3JX', 1437);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-5AFJDM', 9295);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-2KHGM0', 2047);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-2GZ2LL', 1294);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-7UI7U5', 2092);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2K0CVA', 7655);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-6N1ISE', 3824);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-8SML0F', 6668);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-2TUPQ1', 7757);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-0M85CY', 4701);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-8I06ZU', 4763);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-3W70PA', 3579);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5RPGRQ', 7376);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-68XZ5N', 6240);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-6QYPKI', 2209);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-25BRI9', 3109);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-3IB76M', 2704);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-1HVXGQ', 9615);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-4P25YS', 6219);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-039TV5', 9143);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-18E6PB', 2087);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-5U2N5M', 7794);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4DL30K', 4287);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-4P5RR7', 6315);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-5CFM8D', 9066);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-1BL8ZS', 4463);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-91Z2KQ', 557);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0J004W', 3601);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-80FG9M', 579);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-0XC9ZM', 1407);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-84CEGV', 8001);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-4LSTD0', 8379);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-7LCDF5', 8652);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-27KX7E', 5441);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-9ZBWXH', 2714);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-1D4D9X', 7511);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-94YU8C', 977);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-0CWIPL', 5500);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-6SPDRX', 3774);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-2P5NW6', 8372);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-0GS160', 7529);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-7YK6ST', 3897);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-9TCX7N', 4885);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-50XHSM', 7645);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-1FVGRP', 2331);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-3U3FBA', 2812);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-9NAQ5B', 6180);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-2RRLZL', 8065);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-8EXJWL', 2136);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-3ALAV3', 8147);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-7Y69BZ', 12);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-9DUSM2', 7187);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-3ZL4IZ', 9728);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-37USE2', 4783);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-7VGAY1', 6166);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-2FNEED', 5451);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-6E4KRR', 285);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-3S86ID', 4199);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-6RG1EC', 4884);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-6HS8GS', 921);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-76HPHD', 3788);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-9UM9B0', 8536);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-19B4M5', 2685);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-1B7HN1', 7859);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-9H30CY', 1885);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-47LGDV', 4672);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-830GWD', 3830);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-2GYHZT', 9337);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-4548R2', 5405);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-9861PB', 8107);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3R3AW1', 164);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-5XU0R4', 212);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-9U8JU4', 5318);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-698ETI', 8497);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-3V4F1K', 4958);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-6W67B3', 110);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-0VM7D2', 4328);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-7FAY2A', 2780);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-0ZNU1G', 342);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-3IHP9R', 7467);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-54Q29F', 2403);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-81PIL3', 4573);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-9GCG0Y', 8195);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-72CVFS', 5983);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-2BJW2N', 3262);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-02CUP9', 398);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-89VLKS', 8706);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-0EGKG4', 4480);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-6IV2MN', 2771);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-4HXK5A', 4659);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-8203NH', 165);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-34D6AD', 9008);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-0PA8AB', 7780);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-10U3A9', 3838);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-9KR0LV', 4563);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-27EJWV', 5837);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-68D7RV', 6642);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-95D6M5', 6970);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-9AQHLU', 4365);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-8LVEJ1', 5663);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-4TG1IH', 6139);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-4DS1XX', 9709);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-69V7Y4', 9538);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-6F8H82', 229);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-67V2VL', 2141);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-6AWDTY', 8784);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0UAR5C', 8362);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-7TVVPY', 2467);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-685JY5', 5384);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-18DKPT', 8458);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-0DMIKN', 2995);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-05B4L9', 7332);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-5AK9JJ', 663);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-7ZTHEJ', 8501);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-1FPI7A', 6104);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-25LWNZ', 6023);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-9HCPDS', 6964);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-7HXNS4', 5331);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-2QCZIS', 448);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-6376XH', 6879);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0G074G', 1213);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-9LB081', 9408);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-1FKEIY', 708);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-5DLAEC', 6842);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-23QH8A', 9881);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-7Y2Q2W', 4676);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-090MDI', 9751);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-6FC2AA', 8504);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-6EVDHQ', 571);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-4BG89T', 795);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-49Y03Y', 2577);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-5XSSNB', 6048);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-5QVY9G', 9218);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-6ZU4JK', 9990);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-12NNC1', 3798);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-16MBAM', 3972);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-2RKB0C', 6764);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-16EXH0', 7385);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-1JRD0Q', 3877);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0QHETQ', 6630);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-87YRDJ', 1177);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-7KAQ5Y', 84);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-9KDGEX', 9999);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-8IZ8DG', 3120);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-4PFZ3Z', 1755);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-29IWM0', 9809);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-2PQX7F', 4364);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-7ABSCX', 4885);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-64NWYR', 5117);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-21ZK9T', 5216);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0Z45G4', 6013);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-6U9RMI', 5225);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-3NU9WK', 5209);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-7EJ61K', 959);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-2T101P', 4854);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-7HU6SK', 6444);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-4AQA8P', 439);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-8G6L2L', 6163);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-067GPC', 6935);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-9FPW7F', 2187);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-9F1KCK', 6150);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-0ZHCKB', 3287);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川G-8KPADG', 8621);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-1A63SL', 1016);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-7XRRA1', 879);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-193JI2', 2744);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-3KIR14', 2716);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-80DVGQ', 2517);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-273EMG', 4775);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-7FEFQZ', 9346);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-8R2WMV', 4142);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-83G2K0', 8577);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川B-5LEE98', 6172);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-5JJPFQ', 7767);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-59NQAG', 3011);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川A-5Z1M4N', 348);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川E-6Y8MEV', 9154);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-4LXLIE', 2203);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-8FV0G4', 3229);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川D-278I67', 5508);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川F-15CIVP', 6056);\
    INSERT INTO `all_cars` (plate, balance) VALUES ('川H-9KW5RK', 6517);\
")



cursor.close()
connection.commit()
connection.close()
